version: '3'

services:
  app:
    build: .
    container_name: codarme
    ports:
      - "8000:8000"
    volumes:
      - .:/home/python/app
  redis:
    image: redis
    container_name: redis
    command: redis-server /usr/local/etc/redis/redis.conf
    expose:
      - "6379"
    ports:
      - "6379:6379"
    volumes:
      - ./data:/data
      - ./redis.conf:/usr/local/etc/redis/redis.conf